/*
 * Copyright (c) 2026 Teenygrad.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//! GPU kernel execution tests for the teenyformers custom ops.
//!
//! Each test:
//!   1. Loads binary fixtures generated by `tests/fixtures/generate.py`.
//!   2. Compiles the Triton kernel to PTX.
//!   3. Runs it on the GPU.
//!   4. Compares the output against the PyTorch-generated fixture.
//!
//! These tests require the `cuda` feature and a CUDA-capable device.
//! They are skipped silently if no GPU is present.

#[cfg(feature = "cuda")]
mod cuda_tests {
    use dotenv::dotenv;
    use teeny_compiler::compiler::{driver::cuda::compile_kernel, target::cuda::Target};
    use teeny_core::device::Device;
    use teeny_core::device::buffer::Buffer;
    use teeny_cuda::{device::CudaLaunchConfig, errors::Result, testing};

    const TOLERANCE: f32 = 1e-4;
    const BLOCK_N:   i32 = 16;    // covers all test fixtures (d_ff ≤ 16, N ≤ 16)
    const HEAD_DIM:  i32 = 16;    // rope fixture head_dim

    fn load_fixture(rel: &str) -> Vec<f32> {
        let path = format!("{}/tests/fixtures/{}", env!("CARGO_MANIFEST_DIR"), rel);
        let bytes = std::fs::read(&path)
            .unwrap_or_else(|e| panic!("missing fixture {path}: {e}"));
        bytes
            .chunks_exact(4)
            .map(|b| f32::from_le_bytes([b[0], b[1], b[2], b[3]]))
            .collect()
    }

    fn check_close(name: &str, got: &[f32], expected: &[f32]) {
        assert_eq!(got.len(), expected.len(), "{name}: length mismatch");
        for (i, (g, e)) in got.iter().zip(expected.iter()).enumerate() {
            assert!(
                (g - e).abs() < TOLERANCE,
                "{name}[{i}]: got {g:.6} expected {e:.6} diff {:.6}",
                (g - e).abs(),
            );
        }
    }

    // ── SwiGLU forward ───────────────────────────────────────────────────────────

    #[test]
    fn test_swiglu_forward_cuda() -> Result<()> {
        dotenv().ok();
        let env = testing::setup_cuda_env()?;
        let device = &env.device;

        // Fixture: z [4, 16], out [4, 8]
        const M: usize = 4;
        const D_FF: usize = 8;
        let z_host   = load_fixture("swiglu/input.bin");
        let expected = load_fixture("swiglu/output.bin");
        assert_eq!(z_host.len(),   M * 2 * D_FF);
        assert_eq!(expected.len(), M * D_FF);

        let mut z_buf  = device.buffer::<f32>(M * 2 * D_FF)?;
        let out_buf    = device.buffer::<f32>(M * D_FF)?;
        z_buf.to_device(&z_host)?;

        let kernel = teenyformers::kernels::swiglu::SwigluForward::<f32>::new(BLOCK_N);
        let target = Target::new(env.capability);
        let ptx_path = compile_kernel(&kernel, &target, true)?;
        let ptx = std::fs::read(&ptx_path)?;
        let program = testing::load_program_from_ptx::<
            teenyformers::kernels::swiglu::SwigluForward<f32>,
        >(&ptx)?;

        let cfg = CudaLaunchConfig {
            grid:    [M as u32, 1, 1],
            block:   [128, 1, 1],
            cluster: [1, 1, 1],
        };
        device.launch(&program, &cfg, (
            z_buf.as_device_ptr() as *mut f32,
            out_buf.as_device_ptr() as *mut f32,
            M as i32,
            D_FF as i32,
        ))?;

        let mut out_host = vec![0.0f32; M * D_FF];
        out_buf.to_host(&mut out_host)?;
        check_close("swiglu_forward", &out_host, &expected);
        Ok(())
    }

    // ── FusedAddRmsNorm forward ───────────────────────────────────────────────────

    #[test]
    fn test_fused_add_rmsnorm_forward_cuda() -> Result<()> {
        dotenv().ok();
        let env = testing::setup_cuda_env()?;
        let device = &env.device;

        // Fixture: x [4, 16], residual [4, 16], weight [16], output_y [4, 16]
        const M: usize = 4;
        const N: usize = 16;
        const EPS: f32 = 1e-6;

        let x_host   = load_fixture("fused_add_rmsnorm/input_x.bin");
        let r_host   = load_fixture("fused_add_rmsnorm/input_residual.bin");
        let w_host   = load_fixture("fused_add_rmsnorm/weight.bin");
        let exp_y    = load_fixture("fused_add_rmsnorm/output_y.bin");

        let mut x_buf    = device.buffer::<f32>(M * N)?;
        let mut r_buf    = device.buffer::<f32>(M * N)?;
        let mut w_buf    = device.buffer::<f32>(N)?;
        let y_buf        = device.buffer::<f32>(M * N)?;
        let h_buf        = device.buffer::<f32>(M * N)?;
        let rstd_buf     = device.buffer::<f32>(M)?;

        x_buf.to_device(&x_host)?;
        r_buf.to_device(&r_host)?;
        w_buf.to_device(&w_host)?;

        let kernel = teenyformers::kernels::fused_add_rmsnorm::FusedAddRmsnormForward::<f32>::new(BLOCK_N);
        let target = Target::new(env.capability);
        let ptx_path = compile_kernel(&kernel, &target, true)?;
        let ptx = std::fs::read(&ptx_path)?;
        let program = testing::load_program_from_ptx::<
            teenyformers::kernels::fused_add_rmsnorm::FusedAddRmsnormForward<f32>,
        >(&ptx)?;

        let cfg = CudaLaunchConfig {
            grid:    [M as u32, 1, 1],
            block:   [128, 1, 1],
            cluster: [1, 1, 1],
        };
        device.launch(&program, &cfg, (
            x_buf.as_device_ptr() as *mut f32,
            r_buf.as_device_ptr() as *mut f32,
            y_buf.as_device_ptr() as *mut f32,
            h_buf.as_device_ptr() as *mut f32,
            rstd_buf.as_device_ptr() as *mut f32,
            w_buf.as_device_ptr() as *mut f32,
            M as i32,
            N as i32,
            EPS,
        ))?;

        let mut y_host = vec![0.0f32; M * N];
        y_buf.to_host(&mut y_host)?;
        check_close("fused_add_rmsnorm_forward", &y_host, &exp_y);
        Ok(())
    }

    // ── RoPE forward ─────────────────────────────────────────────────────────────

    #[test]
    fn test_rope_forward_cuda() -> Result<()> {
        dotenv().ok();
        let env = testing::setup_cuda_env()?;
        let device = &env.device;

        // Fixture: x [2, 8, 16] (bh=2, s=8, head_dim=16)
        const BH: usize = 2;
        const S:  usize = 8;
        const D:  usize = 16; // head_dim
        const ROPE_BASE: f32 = 10_000.0;
        const N: usize = BH * S * D;

        let x_host   = load_fixture("rope/input.bin");
        let expected = load_fixture("rope/output.bin");
        assert_eq!(x_host.len(),   N);
        assert_eq!(expected.len(), N);

        let mut x_buf = device.buffer::<f32>(N)?;
        let y_buf     = device.buffer::<f32>(N)?;
        x_buf.to_device(&x_host)?;

        let kernel = teenyformers::kernels::rope::RopeForward::new(HEAD_DIM);
        let target = Target::new(env.capability);
        let ptx_path = compile_kernel(&kernel, &target, true)?;
        let ptx = std::fs::read(&ptx_path)?;
        let program = testing::load_program_from_ptx::<
            teenyformers::kernels::rope::RopeForward,
        >(&ptx)?;

        let cfg = CudaLaunchConfig {
            grid:    [S as u32, BH as u32, 1],
            block:   [128, 1, 1],
            cluster: [1, 1, 1],
        };
        device.launch(&program, &cfg, (
            x_buf.as_device_ptr() as *mut f32,
            y_buf.as_device_ptr() as *mut f32,
            S as i32,
            ROPE_BASE.ln(),   // kernel takes ln(rope_base), not rope_base
        ))?;

        let mut y_host = vec![0.0f32; N];
        y_buf.to_host(&mut y_host)?;
        check_close("rope_forward", &y_host, &expected);
        Ok(())
    }
}
